const currencyNames = {
    USD: "United States Dollar",
    EUR: "Euro",
    GBP: "British Pound",
    JPY: "Japanese Yen",
    AUD: "Australian Dollar",
    CAD: "Canadian Dollar",
    CHF: "Swiss Franc",
    CNY: "Chinese Yuan Renminbi",
    SEK: "Swedish Krona",
    NZD: "New Zealand Dollar",
    MXN: "Mexican Peso",
    SGD: "Singapore Dollar",
    HKD: "Hong Kong Dollar",
    NOK: "Norwegian Krone",
    KRW: "South Korean Won",
    TRY: "Turkish Lira",
    RUB: "Russian Ruble",
    INR: "Indian Rupee",
    BRL: "Brazilian Real",
    ZAR: "South African Rand",
    AED: "United Arab Emirates Dirham",
    ARS: "Argentine Peso",
    BGN: "Bulgarian Lev",
    CLP: "Chilean Peso",
    COP: "Colombian Peso",
    CZK: "Czech Koruna",
    DKK: "Danish Krone",
    EGP: "Egyptian Pound",
    HUF: "Hungarian Forint",
    IDR: "Indonesian Rupiah",
    ILS: "Israeli Shekel",
    KWD: "Kuwaiti Dinar",
    MYR: "Malaysian Ringgit",
    PHP: "Philippine Peso",
    PKR: "Pakistani Rupee",
    PLN: "Polish Zloty",
    RON: "Romanian Leu",
    SAR: "Saudi Riyal",
    THB: "Thai Baht",
    TWD: "Taiwan Dollar",
    VND: "Vietnamese Dong",
    KZT: "Kazakhstani Tenge",
    UAH: "Ukrainian Hryvnia",
    GEL: "Georgian Lari",
    IQD: "Iraqi Dinar",
    JOD: "Jordanian Dinar",
    LBP: "Lebanese Pound",
    MAD: "Moroccan Dirham",
    OMR: "Omani Rial",
    QAR: "Qatari Riyal",
    XAF: "Central African CFA Franc",
    XCD: "East Caribbean Dollar",
    XOF: "West African CFA Franc",
    XPF: "CFP Franc",
    TND: "Tunisian Dinar",
    LKR: "Sri Lankan Rupee",
    BHD: "Bahraini Dinar",
    MUR: "Mauritian Rupee",
    MGA: "Malagasy Ariary",
    BDT: "Bangladeshi Taka",
    NPR: "Nepalese Rupee",
    BYN: "Belarusian Ruble",
    ISK: "Icelandic Krona",
    MKD: "Macedonian Denar",
    AMD: "Armenian Dram",
    AZN: "Azerbaijani Manat",
    MNT: "Mongolian Tugrik",
    KGS: "Kyrgyzstani Som",
    TJS: "Tajikistani Somoni",
    UZS: "Uzbekistani Som",
    BOB: "Bolivian Boliviano",
    PEN: "Peruvian Sol",
    GHS: "Ghanaian Cedi",
    NGN: "Nigerian Naira",
    ETB: "Ethiopian Birr",
    ZMW: "Zambian Kwacha",
    DZD: "Algerian Dinar",
    SDG: "Sudanese Pound",
    SYP: "Syrian Pound",
    SOS: "Somali Shilling",
    MZN: "Mozambican Metical",
    AFN: "Afghan Afghani"
    // Добавьте еще, если требуется
};

export default currencyNames;
